import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { SplashScreen } from "./splash-screen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <SplashScreen />
      </body>
    </html>
  );
}
